//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeMachineProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoffeeType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Water { get; set; }
        public decimal Sugar { get; set; }
        public decimal Coffee { get; set; }
        public decimal Price { get; set; }
    }
}
